[build]
  publish = "public"
  command = ""
  ignore = "exit 0"

# Disable processing of package.json
[build.environment]
  NODE_ENV = "production"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 